# Generated by Django 5.1.2 on 2024-11-04 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"verbose_name": "Игра", "verbose_name_plural": "Игры"},
        ),
        migrations.AlterField(
            model_name="game",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="duration_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="games.duration",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="game",
            name="full_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
