# Generated by Django 5.1.3 on 2026-08-30 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_rename_competencies_competency"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={
                "ordering": ["name"],
                "verbose_name": "Автор",
                "verbose_name_plural": "Авторы",
            },
        ),
        migrations.AlterModelOptions(
            name="competency",
            options={
                "ordering": ["name"],
                "verbose_name": "Компетенция",
                "verbose_name_plural": "Компетенции",
            },
        ),
        migrations.AlterModelOptions(
            name="duration",
            options={
                "ordering": ["name"],
                "verbose_name": "Длительность",
                "verbose_name_plural": "Длительности",
            },
        ),
        migrations.AlterModelOptions(
            name="game",
            options={
                "ordering": ["title"],
                "verbose_name": "Игра",
                "verbose_name_plural": "Игры",
            },
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={
                "ordering": ["name"],
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
            },
        ),
        migrations.AlterModelOptions(
            name="mode",
            options={
                "ordering": ["name"],
                "verbose_name": "Режим",
                "verbose_name_plural": "Режимы",
            },
        ),
        migrations.AlterModelOptions(
            name="platform",
            options={
                "ordering": ["name"],
                "verbose_name": "Платформа",
                "verbose_name_plural": "Платформы",
            },
        ),
        migrations.AlterModelOptions(
            name="screenshot",
            options={
                "ordering": ["id"],
                "verbose_name": "Скриншот",
                "verbose_name_plural": "Скриншоты",
            },
        ),
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="competency",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="duration",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games",
                to="games.author",
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="competencies",
            field=models.ManyToManyField(
                to="games.competency", verbose_name="Компетенции"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="cover_image",
            field=models.ImageField(upload_to="games/", verbose_name="Обложка"),
        ),
        migrations.AlterField(
            model_name="game",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="game",
            name="duration",
            field=models.CharField(max_length=255, verbose_name="Длительность"),
        ),
        migrations.AlterField(
            model_name="game",
            name="duration_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="games",
                to="games.duration",
                verbose_name="Тип длительности",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="genres",
            field=models.ManyToManyField(to="games.genre", verbose_name="Жанры"),
        ),
        migrations.AlterField(
            model_name="game",
            name="modes",
            field=models.ManyToManyField(to="games.mode", verbose_name="Режимы"),
        ),
        migrations.AlterField(
            model_name="game",
            name="platforms",
            field=models.ManyToManyField(to="games.platform", verbose_name="Платформы"),
        ),
        migrations.AlterField(
            model_name="game",
            name="title",
            field=models.TextField(unique=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="mode",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="screenshot",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="screen_shots",
                to="games.game",
                verbose_name="Игра",
            ),
        ),
        migrations.AlterField(
            model_name="screenshot",
            name="screen_shot",
            field=models.ImageField(upload_to="games/", verbose_name="Скриншот"),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["created_at"], name="game_created_at_idx"),
        ),
    ]
